# Generated by Django 2.0.1 on 2018-03-15 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('video_name', models.CharField(max_length=50, verbose_name='视频标题')),
                ('video_desc', models.TextField(verbose_name='视频描述')),
                ('publish_time', models.DateField(blank=True, null=True, verbose_name='上映时间')),
                ('is_serial', models.BooleanField(default=False, verbose_name='是否是剧集')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tag_id', models.ManyToManyField(to='tag.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'video',
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
