# Generated by Django 2.0.1 on 2018-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='标题')),
                ('content', models.TextField(max_length=250, verbose_name='内容')),
                ('actions', models.CharField(choices=[('oa', '打开APP'), ('op', '打开指定页面')], default='打开APP', max_length=2, verbose_name='点击通知操作')),
                ('scope', models.CharField(choices=[('all', 'All'), ('android', 'Android'), ('ios', 'iOS')], default='All', max_length=7, verbose_name='用户范围')),
                ('time', models.CharField(choices=[('immediate', '立即推送'), ('timing', '定时推送')], default='立即推送', max_length=10, verbose_name='推送时间')),
                ('icon', models.ImageField(height_field=45, upload_to='icon', verbose_name='图标', width_field=45)),
                ('available', models.BooleanField(default=False, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '消息推送管理',
                'verbose_name_plural': '消息推送管理',
                'db_table': 'message',
                'get_latest_by': 'edited_at',
            },
        ),
    ]
