# Generated by Django 2.0.1 on 2018-03-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='icon',
        ),
    ]
