# Generated by Django 2.0.1 on 2018-03-26 07:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity_type', models.CharField(choices=[('P', 'Phone'), ('W', 'Weibo'), ('C', 'WeChat'), ('Q', 'QQ'), ('E', 'Email')], default='Phone', max_length=1, verbose_name='登录类型')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('credential', models.CharField(max_length=250, verbose_name='密码')),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '客户认证',
                'verbose_name_plural': '客户认证',
                'db_table': 'client_auth',
                'get_latest_by': 'identity_type',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.ClientAuth', verbose_name='客户id')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
            ],
            options={
                'verbose_name': '客户详情',
                'verbose_name_plural': '客户详情',
                'db_table': 'client',
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.ClientAuth', verbose_name='客户id')),
                ('msg_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
