# Generated by Django 2.0.1 on 2018-03-26 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttoken',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'verbose_name': '客户token', 'verbose_name_plural': '客户token'},
        ),
        migrations.AddField(
            model_name='clienttoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='msg_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='消息token'),
        ),
        migrations.AlterModelTable(
            name='clienttoken',
            table='client_token',
        ),
    ]
